name: Ballerina PR validation
on: [pull_request, push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Set up go
      uses: actions/setup-go@v1
      with:
        go-version: '1.10.4'
    - name: Set up ruby
      uses: clupprich/ruby-build-action@master
      id: ruby
      with:
        ruby-version: 2.5

    - name: Clone the ballerina-release repo
      run: git clone https://github.com/ballerina-platform/ballerina-release.git
    - name: Go to the ballerina example tool folder 
      run: cd ballerinaByExample
    - name: Execute the bash file
      run: tools/build-bbe.sh bbe_gen_tool v1-0

    - name: Clone the ballerina-dev-website repo
      run: git clone https://github.com/ballerina-platform/ballerina-dev-website.git
    - name: Install Jekyll and bundler gems
      run: gem install jekyll bundler
    - name: Go to the cloned folder
      run: cd ballerina-dev-website
    - name: Build the site and make it available on a local server
      run: bundle exec jekyll serve
      
      
