name: Push Standard Libraries to Stage and Dev Centrals

on:
  workflow_dispatch:
      inputs:
        releaseVersion:
          description: 'Version of the release. e.g., swan-lake-beta1'
          required: true
        preReleaseSuffix:
          description: 'The text that will be suffixed to the Git tag. e.g., rc1'
          required: false
          default: ''

jobs:
  push-stdlibs:
    name: Push Standard Libraries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install Python Packages
        run: |
          pip install requests
          pip install retry
          pip install PyGithub
      - name: Set Version
        id: set-version
        run: |
          RELEASE_VERSION=${{ github.event.inputs.releaseVersion }}
          TAGGED_VERSION=$RELEASE_VERSION
          if [ -n "${{ github.event.inputs.preReleaseSuffix }}" ]; then
            TAGGED_VERSION=$RELEASE_VERSION-${{ github.event.inputs.preReleaseSuffix }}
          fi
          echo VERSION=$RELEASE_VERSION >> $GITHUB_ENV
          echo GIT_TAG=$TAGGED_VERSION >> $GITHUB_ENV
          echo "::set-output name=version::$RELEASE_VERSION"
          echo "::set-output name=taggedVersion::$TAGGED_VERSION"
      - name: Build Modules and Push
        run: |
          python dependabot/stage_dev_push_stdlibs.py ${{ steps.set-version.outputs.taggedVersion }}
        env:
          BALLERINA_BOT_USERNAME: ${{ secrets.BALLERINA_BOT_USERNAME }}
          BALLERINA_BOT_TOKEN: ${{ secrets.BALLERINA_BOT_TOKEN }}
          BALLERINA_BOT_EMAIL: ${{ secrets.BALLERINA_BOT_EMAIL }}
          BALLERINA_REVIEWER_BOT_TOKEN: ${{ secrets.BALLERINA_REVIEWER_BOT_TOKEN }}
