name: Update Dependency Version in Pipeline

on:
  workflow_dispatch:
    inputs:
#      isRetrigger:
#        description: 'Re-trigger a failed dependency bump workflow'
#        required: false
#        default: 'false'
      ballerinaVersion:
        description: 'Ballerina Version (Optional)'
        required: false
        default: ''
      autoMergePRs:
        description: 'Auto Merge PRs'
        required: false
        default: 'true'

jobs:
  update-lang-version:
    name: Update Ballerina Lang Version
    if: github.repository_owner == 'ballerina-platform'
    runs-on: ubuntu-latest
    steps:
      -   name: Checkout Repository
          uses: actions/checkout@v2

      -   name: Setup Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.x'

      -   name: Install Python Packages
          run: |
            pip install requests
            pip install retry
            pip install PyGithub

      -   name: Update Ballerina Language Version
          run: |
            python dependabot/update_dependencies_version.py "false" "${{ github.event.inputs.ballerinaVersion }}" "${{ github.event.inputs.autoMergePRs }}"
          env:
            packageUser: ${{ secrets.BALLERINA_BOT_USERNAME }}
            packagePAT: ${{ secrets.BALLERINA_BOT_TOKEN }}
            packageEmail: ${{ secrets.BALLERINA_BOT_EMAIL }}
            reviewerPackagePAT: ${{ secrets.BALLERINA_REVIEWER_BOT_TOKEN }}
